# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle


variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone
  EXECUTABLE_TO_DEPLOY:"SRVIS/SRVIS.jar"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd srvis

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:11-jre-slim
  script: ./gradlew assemble
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  image: openjdk:11-jre-slim
  script: ./gradlew check
  tags:
    - dalfcs_gitlab_docker_ci

deploy:
  stage: deploy
  image: alpine:latest
  script:
   - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${EXECUTABLE_TO_DEPLOY} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/"
  only:
   - master
   - develop
  tags:
   - dalfcs_gitlab_docker_ci

