# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle


variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:8-jdk
  script: ./gradlew assemble
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  image: openjdk:8-jdk
  script: ./gradlew check
  tags:
    - dalfcs_gitlab_docker_ci

deploy:
  stage: deploy
  image: ruby:latest
  script:
   - apt-get update -qy
   - apt-get install -y ruby-dev
   - gem install dpl
   - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
   - master
   - develop 
  tags:
   - dalfcs_gitlab_docker_ci
